name: MiniGameManager
version: '2.1.1-SNAPSHOT'
main: xyz.leafing.miniGameManager.MiniGameManager
api-version: '1.21'
depend: [NBTAPI]
commands:
  mgm:
    description: Main command for MiniGameManager debugging.
    usage: /<command> [args]
    aliases: [minigamemanager]